// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_respond.proto

#ifndef PROTOBUF_action_5frespond_2eproto__INCLUDED
#define PROTOBUF_action_5frespond_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace network {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_action_5frespond_2eproto();
void protobuf_AssignDesc_action_5frespond_2eproto();
void protobuf_ShutdownFile_action_5frespond_2eproto();

class CharactorPickRequest;
class Pick;
class TurnBegin;
class Action;
class Respond;
class Command;
class CommandRequest;
class ErrorInput;
class HitMsg;

enum MessageType2 {
  MSG_PICK_REQ = 101,
  MSG_PICK = 102,
  MSG_ACTION = 103,
  MSG_RESPOND = 104,
  MSG_CMD_REQ = 106,
  MSG_ERROR_INPUT = 107,
  MSG_HIT = 108,
  MSG_TURN_BEGIN = 109
};
bool MessageType2_IsValid(int value);
const MessageType2 MessageType2_MIN = MSG_PICK_REQ;
const MessageType2 MessageType2_MAX = MSG_TURN_BEGIN;
const int MessageType2_ARRAYSIZE = MessageType2_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType2_descriptor();
inline const ::std::string& MessageType2_Name(MessageType2 value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType2_descriptor(), value);
}
inline bool MessageType2_Parse(
    const ::std::string& name, MessageType2* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType2>(
    MessageType2_descriptor(), name, value);
}
enum BasicActionType {
  ACTION_BUY = 1,
  ACTION_REFINE = 2,
  ACTION_COMPOSE = 3,
  ACTION_ATTACK = 4,
  ACTION_MAGIC = 5,
  ACTION_ANY = 6,
  ACTION_ATTACK_MAGIC = 7,
  ACTION_NONE = 100000
};
bool BasicActionType_IsValid(int value);
const BasicActionType BasicActionType_MIN = ACTION_BUY;
const BasicActionType BasicActionType_MAX = ACTION_NONE;
const int BasicActionType_ARRAYSIZE = BasicActionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BasicActionType_descriptor();
inline const ::std::string& BasicActionType_Name(BasicActionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BasicActionType_descriptor(), value);
}
inline bool BasicActionType_Parse(
    const ::std::string& name, BasicActionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BasicActionType>(
    BasicActionType_descriptor(), name, value);
}
enum BasicRespondType {
  RESPOND_REPLY_ATTACK = 10,
  RESPOND_BULLET = 11,
  RESPOND_HEAL = 12,
  RESPOND_DISCARD = 13,
  RESPOND_WEAKEN = 14
};
bool BasicRespondType_IsValid(int value);
const BasicRespondType BasicRespondType_MIN = RESPOND_REPLY_ATTACK;
const BasicRespondType BasicRespondType_MAX = RESPOND_WEAKEN;
const int BasicRespondType_ARRAYSIZE = BasicRespondType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BasicRespondType_descriptor();
inline const ::std::string& BasicRespondType_Name(BasicRespondType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BasicRespondType_descriptor(), value);
}
inline bool BasicRespondType_Parse(
    const ::std::string& name, BasicRespondType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BasicRespondType>(
    BasicRespondType_descriptor(), name, value);
}
enum CmdType {
  CMD_ACTION = 1,
  CMD_RESPOND = 2
};
bool CmdType_IsValid(int value);
const CmdType CmdType_MIN = CMD_ACTION;
const CmdType CmdType_MAX = CMD_RESPOND;
const int CmdType_ARRAYSIZE = CmdType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CmdType_descriptor();
inline const ::std::string& CmdType_Name(CmdType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CmdType_descriptor(), value);
}
inline bool CmdType_Parse(
    const ::std::string& name, CmdType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdType>(
    CmdType_descriptor(), name, value);
}
// ===================================================================

class CharactorPickRequest : public ::google::protobuf::Message {
 public:
  CharactorPickRequest();
  virtual ~CharactorPickRequest();

  CharactorPickRequest(const CharactorPickRequest& from);

  inline CharactorPickRequest& operator=(const CharactorPickRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CharactorPickRequest& default_instance();

  void Swap(CharactorPickRequest* other);

  // implements Message ----------------------------------------------

  CharactorPickRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CharactorPickRequest& from);
  void MergeFrom(const CharactorPickRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 role_ids = 1;
  inline int role_ids_size() const;
  inline void clear_role_ids();
  static const int kRoleIdsFieldNumber = 1;
  inline ::google::protobuf::uint32 role_ids(int index) const;
  inline void set_role_ids(int index, ::google::protobuf::uint32 value);
  inline void add_role_ids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      role_ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_role_ids();

  // @@protoc_insertion_point(class_scope:network.CharactorPickRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > role_ids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static CharactorPickRequest* default_instance_;
};
// -------------------------------------------------------------------

class Pick : public ::google::protobuf::Message {
 public:
  Pick();
  virtual ~Pick();

  Pick(const Pick& from);

  inline Pick& operator=(const Pick& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pick& default_instance();

  void Swap(Pick* other);

  // implements Message ----------------------------------------------

  Pick* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pick& from);
  void MergeFrom(const Pick& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 role_id() const;
  inline void set_role_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:network.Pick)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 role_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static Pick* default_instance_;
};
// -------------------------------------------------------------------

class TurnBegin : public ::google::protobuf::Message {
 public:
  TurnBegin();
  virtual ~TurnBegin();

  TurnBegin(const TurnBegin& from);

  inline TurnBegin& operator=(const TurnBegin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TurnBegin& default_instance();

  void Swap(TurnBegin* other);

  // implements Message ----------------------------------------------

  TurnBegin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TurnBegin& from);
  void MergeFrom(const TurnBegin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:network.TurnBegin)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static TurnBegin* default_instance_;
};
// -------------------------------------------------------------------

class Action : public ::google::protobuf::Message {
 public:
  Action();
  virtual ~Action();

  Action(const Action& from);

  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Action& default_instance();

  void Swap(Action* other);

  // implements Message ----------------------------------------------

  Action* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Action& from);
  void MergeFrom(const Action& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 action_id = 1;
  inline bool has_action_id() const;
  inline void clear_action_id();
  static const int kActionIdFieldNumber = 1;
  inline ::google::protobuf::uint32 action_id() const;
  inline void set_action_id(::google::protobuf::uint32 value);

  // repeated uint32 args = 2;
  inline int args_size() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 2;
  inline ::google::protobuf::uint32 args(int index) const;
  inline void set_args(int index, ::google::protobuf::uint32 value);
  inline void add_args(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      args() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_args();

  // optional uint32 src_id = 3;
  inline bool has_src_id() const;
  inline void clear_src_id();
  static const int kSrcIdFieldNumber = 3;
  inline ::google::protobuf::uint32 src_id() const;
  inline void set_src_id(::google::protobuf::uint32 value);

  // repeated uint32 dst_ids = 4;
  inline int dst_ids_size() const;
  inline void clear_dst_ids();
  static const int kDstIdsFieldNumber = 4;
  inline ::google::protobuf::uint32 dst_ids(int index) const;
  inline void set_dst_ids(int index, ::google::protobuf::uint32 value);
  inline void add_dst_ids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      dst_ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_dst_ids();

  // @@protoc_insertion_point(class_scope:network.Action)
 private:
  inline void set_has_action_id();
  inline void clear_has_action_id();
  inline void set_has_src_id();
  inline void clear_has_src_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > args_;
  ::google::protobuf::uint32 action_id_;
  ::google::protobuf::uint32 src_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > dst_ids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static Action* default_instance_;
};
// -------------------------------------------------------------------

class Respond : public ::google::protobuf::Message {
 public:
  Respond();
  virtual ~Respond();

  Respond(const Respond& from);

  inline Respond& operator=(const Respond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Respond& default_instance();

  void Swap(Respond* other);

  // implements Message ----------------------------------------------

  Respond* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Respond& from);
  void MergeFrom(const Respond& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 respond_id = 1;
  inline bool has_respond_id() const;
  inline void clear_respond_id();
  static const int kRespondIdFieldNumber = 1;
  inline ::google::protobuf::uint32 respond_id() const;
  inline void set_respond_id(::google::protobuf::uint32 value);

  // repeated uint32 args = 2;
  inline int args_size() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 2;
  inline ::google::protobuf::uint32 args(int index) const;
  inline void set_args(int index, ::google::protobuf::uint32 value);
  inline void add_args(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      args() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_args();

  // optional uint32 src_id = 3;
  inline bool has_src_id() const;
  inline void clear_src_id();
  static const int kSrcIdFieldNumber = 3;
  inline ::google::protobuf::uint32 src_id() const;
  inline void set_src_id(::google::protobuf::uint32 value);

  // repeated uint32 dst_ids = 4;
  inline int dst_ids_size() const;
  inline void clear_dst_ids();
  static const int kDstIdsFieldNumber = 4;
  inline ::google::protobuf::uint32 dst_ids(int index) const;
  inline void set_dst_ids(int index, ::google::protobuf::uint32 value);
  inline void add_dst_ids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      dst_ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_dst_ids();

  // @@protoc_insertion_point(class_scope:network.Respond)
 private:
  inline void set_has_respond_id();
  inline void clear_has_respond_id();
  inline void set_has_src_id();
  inline void clear_has_src_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > args_;
  ::google::protobuf::uint32 respond_id_;
  ::google::protobuf::uint32 src_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > dst_ids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static Respond* default_instance_;
};
// -------------------------------------------------------------------

class Command : public ::google::protobuf::Message {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Command& default_instance();

  void Swap(Command* other);

  // implements Message ----------------------------------------------

  Command* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 respond_id = 1;
  inline bool has_respond_id() const;
  inline void clear_respond_id();
  static const int kRespondIdFieldNumber = 1;
  inline ::google::protobuf::uint32 respond_id() const;
  inline void set_respond_id(::google::protobuf::uint32 value);

  // repeated uint32 args = 2;
  inline int args_size() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 2;
  inline ::google::protobuf::uint32 args(int index) const;
  inline void set_args(int index, ::google::protobuf::uint32 value);
  inline void add_args(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      args() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_args();

  // @@protoc_insertion_point(class_scope:network.Command)
 private:
  inline void set_has_respond_id();
  inline void clear_has_respond_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > args_;
  ::google::protobuf::uint32 respond_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static Command* default_instance_;
};
// -------------------------------------------------------------------

class CommandRequest : public ::google::protobuf::Message {
 public:
  CommandRequest();
  virtual ~CommandRequest();

  CommandRequest(const CommandRequest& from);

  inline CommandRequest& operator=(const CommandRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommandRequest& default_instance();

  void Swap(CommandRequest* other);

  // implements Message ----------------------------------------------

  CommandRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommandRequest& from);
  void MergeFrom(const CommandRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .network.CmdType cmd_type = 1;
  inline bool has_cmd_type() const;
  inline void clear_cmd_type();
  static const int kCmdTypeFieldNumber = 1;
  inline ::network::CmdType cmd_type() const;
  inline void set_cmd_type(::network::CmdType value);

  // repeated .network.Command commands = 2;
  inline int commands_size() const;
  inline void clear_commands();
  static const int kCommandsFieldNumber = 2;
  inline const ::network::Command& commands(int index) const;
  inline ::network::Command* mutable_commands(int index);
  inline ::network::Command* add_commands();
  inline const ::google::protobuf::RepeatedPtrField< ::network::Command >&
      commands() const;
  inline ::google::protobuf::RepeatedPtrField< ::network::Command >*
      mutable_commands();

  // @@protoc_insertion_point(class_scope:network.CommandRequest)
 private:
  inline void set_has_cmd_type();
  inline void clear_has_cmd_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::network::Command > commands_;
  int cmd_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static CommandRequest* default_instance_;
};
// -------------------------------------------------------------------

class ErrorInput : public ::google::protobuf::Message {
 public:
  ErrorInput();
  virtual ~ErrorInput();

  ErrorInput(const ErrorInput& from);

  inline ErrorInput& operator=(const ErrorInput& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ErrorInput& default_instance();

  void Swap(ErrorInput* other);

  // implements Message ----------------------------------------------

  ErrorInput* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ErrorInput& from);
  void MergeFrom(const ErrorInput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .network.CmdType error_type = 1;
  inline bool has_error_type() const;
  inline void clear_error_type();
  static const int kErrorTypeFieldNumber = 1;
  inline ::network::CmdType error_type() const;
  inline void set_error_type(::network::CmdType value);

  // repeated .network.Command commands = 2;
  inline int commands_size() const;
  inline void clear_commands();
  static const int kCommandsFieldNumber = 2;
  inline const ::network::Command& commands(int index) const;
  inline ::network::Command* mutable_commands(int index);
  inline ::network::Command* add_commands();
  inline const ::google::protobuf::RepeatedPtrField< ::network::Command >&
      commands() const;
  inline ::google::protobuf::RepeatedPtrField< ::network::Command >*
      mutable_commands();

  // @@protoc_insertion_point(class_scope:network.ErrorInput)
 private:
  inline void set_has_error_type();
  inline void clear_has_error_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::network::Command > commands_;
  int error_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static ErrorInput* default_instance_;
};
// -------------------------------------------------------------------

class HitMsg : public ::google::protobuf::Message {
 public:
  HitMsg();
  virtual ~HitMsg();

  HitMsg(const HitMsg& from);

  inline HitMsg& operator=(const HitMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HitMsg& default_instance();

  void Swap(HitMsg* other);

  // implements Message ----------------------------------------------

  HitMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HitMsg& from);
  void MergeFrom(const HitMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 cmd_id = 1;
  inline bool has_cmd_id() const;
  inline void clear_cmd_id();
  static const int kCmdIdFieldNumber = 1;
  inline ::google::protobuf::uint32 cmd_id() const;
  inline void set_cmd_id(::google::protobuf::uint32 value);

  // optional uint32 hit = 2;
  inline bool has_hit() const;
  inline void clear_hit();
  static const int kHitFieldNumber = 2;
  inline ::google::protobuf::uint32 hit() const;
  inline void set_hit(::google::protobuf::uint32 value);

  // optional uint32 src_id = 3;
  inline bool has_src_id() const;
  inline void clear_src_id();
  static const int kSrcIdFieldNumber = 3;
  inline ::google::protobuf::uint32 src_id() const;
  inline void set_src_id(::google::protobuf::uint32 value);

  // optional uint32 dst_id = 4;
  inline bool has_dst_id() const;
  inline void clear_dst_id();
  static const int kDstIdFieldNumber = 4;
  inline ::google::protobuf::uint32 dst_id() const;
  inline void set_dst_id(::google::protobuf::uint32 value);

  // optional uint32 damage = 5;
  inline bool has_damage() const;
  inline void clear_damage();
  static const int kDamageFieldNumber = 5;
  inline ::google::protobuf::uint32 damage() const;
  inline void set_damage(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:network.HitMsg)
 private:
  inline void set_has_cmd_id();
  inline void clear_has_cmd_id();
  inline void set_has_hit();
  inline void clear_has_hit();
  inline void set_has_src_id();
  inline void clear_has_src_id();
  inline void set_has_dst_id();
  inline void clear_has_dst_id();
  inline void set_has_damage();
  inline void clear_has_damage();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 cmd_id_;
  ::google::protobuf::uint32 hit_;
  ::google::protobuf::uint32 src_id_;
  ::google::protobuf::uint32 dst_id_;
  ::google::protobuf::uint32 damage_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_action_5frespond_2eproto();
  friend void protobuf_AssignDesc_action_5frespond_2eproto();
  friend void protobuf_ShutdownFile_action_5frespond_2eproto();

  void InitAsDefaultInstance();
  static HitMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// CharactorPickRequest

// repeated uint32 role_ids = 1;
inline int CharactorPickRequest::role_ids_size() const {
  return role_ids_.size();
}
inline void CharactorPickRequest::clear_role_ids() {
  role_ids_.Clear();
}
inline ::google::protobuf::uint32 CharactorPickRequest::role_ids(int index) const {
  return role_ids_.Get(index);
}
inline void CharactorPickRequest::set_role_ids(int index, ::google::protobuf::uint32 value) {
  role_ids_.Set(index, value);
}
inline void CharactorPickRequest::add_role_ids(::google::protobuf::uint32 value) {
  role_ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CharactorPickRequest::role_ids() const {
  return role_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CharactorPickRequest::mutable_role_ids() {
  return &role_ids_;
}

// -------------------------------------------------------------------

// Pick

// optional uint32 role_id = 1;
inline bool Pick::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pick::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pick::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pick::clear_role_id() {
  role_id_ = 0u;
  clear_has_role_id();
}
inline ::google::protobuf::uint32 Pick::role_id() const {
  return role_id_;
}
inline void Pick::set_role_id(::google::protobuf::uint32 value) {
  set_has_role_id();
  role_id_ = value;
}

// -------------------------------------------------------------------

// TurnBegin

// optional uint32 id = 1;
inline bool TurnBegin::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TurnBegin::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TurnBegin::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TurnBegin::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 TurnBegin::id() const {
  return id_;
}
inline void TurnBegin::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// Action

// optional uint32 action_id = 1;
inline bool Action::has_action_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Action::set_has_action_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Action::clear_has_action_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Action::clear_action_id() {
  action_id_ = 0u;
  clear_has_action_id();
}
inline ::google::protobuf::uint32 Action::action_id() const {
  return action_id_;
}
inline void Action::set_action_id(::google::protobuf::uint32 value) {
  set_has_action_id();
  action_id_ = value;
}

// repeated uint32 args = 2;
inline int Action::args_size() const {
  return args_.size();
}
inline void Action::clear_args() {
  args_.Clear();
}
inline ::google::protobuf::uint32 Action::args(int index) const {
  return args_.Get(index);
}
inline void Action::set_args(int index, ::google::protobuf::uint32 value) {
  args_.Set(index, value);
}
inline void Action::add_args(::google::protobuf::uint32 value) {
  args_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Action::args() const {
  return args_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Action::mutable_args() {
  return &args_;
}

// optional uint32 src_id = 3;
inline bool Action::has_src_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Action::set_has_src_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Action::clear_has_src_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Action::clear_src_id() {
  src_id_ = 0u;
  clear_has_src_id();
}
inline ::google::protobuf::uint32 Action::src_id() const {
  return src_id_;
}
inline void Action::set_src_id(::google::protobuf::uint32 value) {
  set_has_src_id();
  src_id_ = value;
}

// repeated uint32 dst_ids = 4;
inline int Action::dst_ids_size() const {
  return dst_ids_.size();
}
inline void Action::clear_dst_ids() {
  dst_ids_.Clear();
}
inline ::google::protobuf::uint32 Action::dst_ids(int index) const {
  return dst_ids_.Get(index);
}
inline void Action::set_dst_ids(int index, ::google::protobuf::uint32 value) {
  dst_ids_.Set(index, value);
}
inline void Action::add_dst_ids(::google::protobuf::uint32 value) {
  dst_ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Action::dst_ids() const {
  return dst_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Action::mutable_dst_ids() {
  return &dst_ids_;
}

// -------------------------------------------------------------------

// Respond

// optional uint32 respond_id = 1;
inline bool Respond::has_respond_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Respond::set_has_respond_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Respond::clear_has_respond_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Respond::clear_respond_id() {
  respond_id_ = 0u;
  clear_has_respond_id();
}
inline ::google::protobuf::uint32 Respond::respond_id() const {
  return respond_id_;
}
inline void Respond::set_respond_id(::google::protobuf::uint32 value) {
  set_has_respond_id();
  respond_id_ = value;
}

// repeated uint32 args = 2;
inline int Respond::args_size() const {
  return args_.size();
}
inline void Respond::clear_args() {
  args_.Clear();
}
inline ::google::protobuf::uint32 Respond::args(int index) const {
  return args_.Get(index);
}
inline void Respond::set_args(int index, ::google::protobuf::uint32 value) {
  args_.Set(index, value);
}
inline void Respond::add_args(::google::protobuf::uint32 value) {
  args_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Respond::args() const {
  return args_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Respond::mutable_args() {
  return &args_;
}

// optional uint32 src_id = 3;
inline bool Respond::has_src_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Respond::set_has_src_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Respond::clear_has_src_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Respond::clear_src_id() {
  src_id_ = 0u;
  clear_has_src_id();
}
inline ::google::protobuf::uint32 Respond::src_id() const {
  return src_id_;
}
inline void Respond::set_src_id(::google::protobuf::uint32 value) {
  set_has_src_id();
  src_id_ = value;
}

// repeated uint32 dst_ids = 4;
inline int Respond::dst_ids_size() const {
  return dst_ids_.size();
}
inline void Respond::clear_dst_ids() {
  dst_ids_.Clear();
}
inline ::google::protobuf::uint32 Respond::dst_ids(int index) const {
  return dst_ids_.Get(index);
}
inline void Respond::set_dst_ids(int index, ::google::protobuf::uint32 value) {
  dst_ids_.Set(index, value);
}
inline void Respond::add_dst_ids(::google::protobuf::uint32 value) {
  dst_ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Respond::dst_ids() const {
  return dst_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Respond::mutable_dst_ids() {
  return &dst_ids_;
}

// -------------------------------------------------------------------

// Command

// optional uint32 respond_id = 1;
inline bool Command::has_respond_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Command::set_has_respond_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Command::clear_has_respond_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Command::clear_respond_id() {
  respond_id_ = 0u;
  clear_has_respond_id();
}
inline ::google::protobuf::uint32 Command::respond_id() const {
  return respond_id_;
}
inline void Command::set_respond_id(::google::protobuf::uint32 value) {
  set_has_respond_id();
  respond_id_ = value;
}

// repeated uint32 args = 2;
inline int Command::args_size() const {
  return args_.size();
}
inline void Command::clear_args() {
  args_.Clear();
}
inline ::google::protobuf::uint32 Command::args(int index) const {
  return args_.Get(index);
}
inline void Command::set_args(int index, ::google::protobuf::uint32 value) {
  args_.Set(index, value);
}
inline void Command::add_args(::google::protobuf::uint32 value) {
  args_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Command::args() const {
  return args_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Command::mutable_args() {
  return &args_;
}

// -------------------------------------------------------------------

// CommandRequest

// optional .network.CmdType cmd_type = 1;
inline bool CommandRequest::has_cmd_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CommandRequest::set_has_cmd_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CommandRequest::clear_has_cmd_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CommandRequest::clear_cmd_type() {
  cmd_type_ = 1;
  clear_has_cmd_type();
}
inline ::network::CmdType CommandRequest::cmd_type() const {
  return static_cast< ::network::CmdType >(cmd_type_);
}
inline void CommandRequest::set_cmd_type(::network::CmdType value) {
  assert(::network::CmdType_IsValid(value));
  set_has_cmd_type();
  cmd_type_ = value;
}

// repeated .network.Command commands = 2;
inline int CommandRequest::commands_size() const {
  return commands_.size();
}
inline void CommandRequest::clear_commands() {
  commands_.Clear();
}
inline const ::network::Command& CommandRequest::commands(int index) const {
  return commands_.Get(index);
}
inline ::network::Command* CommandRequest::mutable_commands(int index) {
  return commands_.Mutable(index);
}
inline ::network::Command* CommandRequest::add_commands() {
  return commands_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::network::Command >&
CommandRequest::commands() const {
  return commands_;
}
inline ::google::protobuf::RepeatedPtrField< ::network::Command >*
CommandRequest::mutable_commands() {
  return &commands_;
}

// -------------------------------------------------------------------

// ErrorInput

// optional .network.CmdType error_type = 1;
inline bool ErrorInput::has_error_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ErrorInput::set_has_error_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ErrorInput::clear_has_error_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ErrorInput::clear_error_type() {
  error_type_ = 1;
  clear_has_error_type();
}
inline ::network::CmdType ErrorInput::error_type() const {
  return static_cast< ::network::CmdType >(error_type_);
}
inline void ErrorInput::set_error_type(::network::CmdType value) {
  assert(::network::CmdType_IsValid(value));
  set_has_error_type();
  error_type_ = value;
}

// repeated .network.Command commands = 2;
inline int ErrorInput::commands_size() const {
  return commands_.size();
}
inline void ErrorInput::clear_commands() {
  commands_.Clear();
}
inline const ::network::Command& ErrorInput::commands(int index) const {
  return commands_.Get(index);
}
inline ::network::Command* ErrorInput::mutable_commands(int index) {
  return commands_.Mutable(index);
}
inline ::network::Command* ErrorInput::add_commands() {
  return commands_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::network::Command >&
ErrorInput::commands() const {
  return commands_;
}
inline ::google::protobuf::RepeatedPtrField< ::network::Command >*
ErrorInput::mutable_commands() {
  return &commands_;
}

// -------------------------------------------------------------------

// HitMsg

// optional uint32 cmd_id = 1;
inline bool HitMsg::has_cmd_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HitMsg::set_has_cmd_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HitMsg::clear_has_cmd_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HitMsg::clear_cmd_id() {
  cmd_id_ = 0u;
  clear_has_cmd_id();
}
inline ::google::protobuf::uint32 HitMsg::cmd_id() const {
  return cmd_id_;
}
inline void HitMsg::set_cmd_id(::google::protobuf::uint32 value) {
  set_has_cmd_id();
  cmd_id_ = value;
}

// optional uint32 hit = 2;
inline bool HitMsg::has_hit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HitMsg::set_has_hit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HitMsg::clear_has_hit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HitMsg::clear_hit() {
  hit_ = 0u;
  clear_has_hit();
}
inline ::google::protobuf::uint32 HitMsg::hit() const {
  return hit_;
}
inline void HitMsg::set_hit(::google::protobuf::uint32 value) {
  set_has_hit();
  hit_ = value;
}

// optional uint32 src_id = 3;
inline bool HitMsg::has_src_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HitMsg::set_has_src_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HitMsg::clear_has_src_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HitMsg::clear_src_id() {
  src_id_ = 0u;
  clear_has_src_id();
}
inline ::google::protobuf::uint32 HitMsg::src_id() const {
  return src_id_;
}
inline void HitMsg::set_src_id(::google::protobuf::uint32 value) {
  set_has_src_id();
  src_id_ = value;
}

// optional uint32 dst_id = 4;
inline bool HitMsg::has_dst_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HitMsg::set_has_dst_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HitMsg::clear_has_dst_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HitMsg::clear_dst_id() {
  dst_id_ = 0u;
  clear_has_dst_id();
}
inline ::google::protobuf::uint32 HitMsg::dst_id() const {
  return dst_id_;
}
inline void HitMsg::set_dst_id(::google::protobuf::uint32 value) {
  set_has_dst_id();
  dst_id_ = value;
}

// optional uint32 damage = 5;
inline bool HitMsg::has_damage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HitMsg::set_has_damage() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HitMsg::clear_has_damage() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HitMsg::clear_damage() {
  damage_ = 0u;
  clear_has_damage();
}
inline ::google::protobuf::uint32 HitMsg::damage() const {
  return damage_;
}
inline void HitMsg::set_damage(::google::protobuf::uint32 value) {
  set_has_damage();
  damage_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace network

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::network::MessageType2>() {
  return ::network::MessageType2_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::network::BasicActionType>() {
  return ::network::BasicActionType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::network::BasicRespondType>() {
  return ::network::BasicRespondType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::network::CmdType>() {
  return ::network::CmdType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_action_5frespond_2eproto__INCLUDED
